language: java

jdk:
- oraclejdk8

addons:
  sonarcloud:
    organization: "brunojsluz"
    token:
      secure: de93df731a1050f796c26e0901b0f617f64280f5
    branches:
      - master
      - develop
script:
  - sonar-scanner